mysite/contacts/urls.py
from django.urls import path
from . import views
from contacts import views as contact_views

app_name='contacts'
urlpatterns = [
    path('upload/', contact_views.upload, name='upload'),
    path('mycontacts/', contact_views.UploadView.as_view(), name='mycontacts'),
    path('delete/<str:pk>/', contact_views.delete, name='delete')
]

mysite/mysite/urls.py
  
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from templates import registration


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('userprofiles.urls')),
    path('', include('contacts.urls')),
    path('admin/', admin.site.urls),  
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
]
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/userprofiles/urls.py
from django.urls import path
from . import views
from userprofiles import views as userprofiles_views

app_name='userprofiles'
urlpatterns = [
    path('', userprofiles_views.home, name='home'),
    path('register/', userprofiles_views.register, name='register'),
    path('profile/', userprofiles_views.ProfileView.as_view(), name='profile'),
    path('edit_profile/', userprofiles_views.ProfileUpdateView.as_view(), name='edit_profile'),
    path('allcenters/', userprofiles_views.getcenters, name='allcenters'),
]

mysite/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <title>{% block title %}Covid-19{% endblock %}</title>
  <style type="text/css">
    .asteriskField {
      display: none;
    }

    form .alert ul li {
      list-style: none;
    }

    form .alert ul {
      padding: 0;
      margin: 0;
    }
    body {
    background: #eee;
}
  </style>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
    <div class="container">
      <a class="navbar-brand" href="{% url 'userprofiles:home' %} "> <img src="\media\covid.jpg" style="width:200px;height:110px;" ></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

        </ul>
        {% if user.is_authenticated %}
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              {{ user.first_name }} {{ user.last_name }}

            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'userprofiles:profile' %}"><i class="fa fa-user-circle" style="font-size:20px"></i> Profile</a>
              <a class="dropdown-item" href="{% url 'userprofiles:edit_profile' %}"><i class="fa fa-vcard" style="font-size:20px"></i> Edit Profile</a>
              <a class="dropdown-item" href="{% url 'password_change' %}"><i class="fa fa-lock" style="font-size:20px"></i> Change password</a>
              <a class="dropdown-item" href="{% url 'contacts:upload' %}"><i class="fa fa-user-plus" style="font-size:20px"></i> Create a Close Contact</a>
              <a class="dropdown-item" href="{% url 'contacts:mycontacts' %}"><i class="fa fa-users" style="font-size:20px"></i> My Close Contacts</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'logout' %}"><i class="fa fa-sign-out" style="font-size:20px"></i> Log out</a>
            </div>
          </li>
        </ul>
        {% else %}
        <form class="form-inline my-2 my-lg-0">
          <a href="{% url 'login' %}" class="btn btn-outline-secondary"><i class="fa fa-sign-in" style="font-size:20px"></i> Log in</a>
          <a href="{% url 'userprofiles:register' %}" class="btn btn-primary ml-2"><i class="fa fa-user-plus" style="font-size:20px"></i> Sign up</a>
        </form>
        {% endif %}
      </div>
    </div>
  </nav>

  <div class="container">
    {% block content %}
    {% endblock %}
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>
    {% block js %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    {% endblock %}
    {% block extrajs %}
    {% endblock %}
</body>

</html>

mysite/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h2>Homepage</h2>
<p>Welcome to Covid-19 Contact Tracing, {% if user.is_authenticated %}{{ user.username }}{% else %}visitor{% endif %}!</p>
<strong>Total users registered: </strong> <i class="fa fa-users" style="font-size:20px"></i> {{ count }} 
<br>
{{allcenters}}
<strong>
  <a href="{% url 'userprofiles:allcenters' %}">Check all Covid-19 Diagnostic Center</a>.</p>
</strong>

{% endblock %}